; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\Projects\TaintAnalysis\AntiTaint\Epilog\src\func.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	__$ArrayPad$
PUBLIC	_func
EXTRN	__imp__printf:PROC
EXTRN	__imp__gets:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Ogtpy
; File d:\projects\taintanalysis\antitaint\epilog\src\func.c
;	COMDAT _func
_TEXT	SEGMENT
_buf$ = -12						; size = 8
__$ArrayPad$ = -4					; size = 4
_func	PROC						; COMDAT

; 10   : {

	sub	esp, 12					; 0000000cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+12], eax

; 11   :   char buf[8];
; 12   :   gets(buf);

	lea	eax, DWORD PTR _buf$[esp+12]
	push	eax
	call	DWORD PTR __imp__gets

; 13   :   printf(buf);

	lea	ecx, DWORD PTR _buf$[esp+16]
	push	ecx
	call	DWORD PTR __imp__printf

; 14   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+20]
	add	esp, 8
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 12					; 0000000cH
	ret	0
_func	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 18   :   func();

	call	_func

; 19   :   return 0;

	xor	eax, eax

; 20   : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
