; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\Projects\TaintAnalysis\AntiTaint\Epilog\src\func-iparam.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG3569	DB	'%d %d %d %s', 0aH, 00H
_DATA	ENDS
PUBLIC	_func
EXTRN	__imp__printf:PROC
EXTRN	__imp__gets:PROC
; Function compile flags: /Odtp
; File d:\projects\taintanalysis\antitaint\epilog\src\func-iparam.c
_TEXT	SEGMENT
_buf$ = -8						; size = 8
_param1$ = 8						; size = 4
_param2$ = 12						; size = 4
_param3$ = 16						; size = 4
_func	PROC

; 9    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 10   :   char buf[8];
; 11   :   gets(buf);

	lea	eax, DWORD PTR _buf$[ebp]
	push	eax
	call	DWORD PTR __imp__gets
	add	esp, 4

; 12   :   printf("%d %d %d %s\n", param1, param2, param3, buf);

	lea	ecx, DWORD PTR _buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _param3$[ebp]
	push	edx
	mov	eax, DWORD PTR _param2$[ebp]
	push	eax
	mov	ecx, DWORD PTR _param1$[ebp]
	push	ecx
	push	OFFSET $SG3569
	call	DWORD PTR __imp__printf
	add	esp, 20					; 00000014H

; 13   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_func	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC

; 16   : {

	push	ebp
	mov	ebp, esp

; 17   :   func(1, 2, 3);

	push	3
	push	2
	push	1
	call	_func
	add	esp, 12					; 0000000cH

; 18   :   return 0;

	xor	eax, eax

; 19   : }

	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
