; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\Projects\TaintAnalysis\AntiTaint\Epilog\src\func-iparam-fastcall.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG3571	DB	'%d %d %d %d %s', 0aH, 00H
_DATA	ENDS
PUBLIC	@func@16
EXTRN	__imp__printf:PROC
EXTRN	__imp__gets:PROC
; Function compile flags: /Odtp
; File d:\projects\taintanalysis\antitaint\epilog\src\func-iparam-fastcall.c
_TEXT	SEGMENT
_param2$ = -16						; size = 4
_param1$ = -12						; size = 4
_buf$ = -8						; size = 8
_param3$ = 8						; size = 4
_param4$ = 12						; size = 4
@func@16 PROC
; _param1$ = ecx
; _param2$ = edx

; 16   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	mov	DWORD PTR _param2$[ebp], edx
	mov	DWORD PTR _param1$[ebp], ecx

; 17   :   char buf[8];
; 18   :   gets(buf);

	lea	eax, DWORD PTR _buf$[ebp]
	push	eax
	call	DWORD PTR __imp__gets
	add	esp, 4

; 19   :   printf("%d %d %d %d %s\n", param1, param2, param3, param4, buf);

	lea	ecx, DWORD PTR _buf$[ebp]
	push	ecx
	mov	edx, DWORD PTR _param4$[ebp]
	push	edx
	mov	eax, DWORD PTR _param3$[ebp]
	push	eax
	mov	ecx, DWORD PTR _param2$[ebp]
	push	ecx
	mov	edx, DWORD PTR _param1$[ebp]
	push	edx
	push	OFFSET $SG3571
	call	DWORD PTR __imp__printf
	add	esp, 24					; 00000018H

; 20   : }

	mov	esp, ebp
	pop	ebp
	ret	8
@func@16 ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC

; 23   : {

	push	ebp
	mov	ebp, esp

; 24   :   func(1, 2, 3, 4);

	push	4
	push	3
	mov	edx, 2
	mov	ecx, 1
	call	@func@16

; 25   :   return 0;

	xor	eax, eax

; 26   : }

	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
