; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\Projects\TaintAnalysis\AntiTaint\Epilog\src\func-iparam.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_0N@FGAKPGKN@?$CFd?5?$CFd?5?$CFd?5?$CFs?6?$AA@ ; `string'
PUBLIC	__$ArrayPad$
PUBLIC	_func
EXTRN	__imp__printf:PROC
EXTRN	__imp__gets:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
;	COMDAT ??_C@_0N@FGAKPGKN@?$CFd?5?$CFd?5?$CFd?5?$CFs?6?$AA@
; File d:\projects\taintanalysis\antitaint\epilog\src\func-iparam.c
CONST	SEGMENT
??_C@_0N@FGAKPGKN@?$CFd?5?$CFd?5?$CFd?5?$CFs?6?$AA@ DB '%d %d %d %s', 0aH
	DB	00H						; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _func
_TEXT	SEGMENT
_buf$ = -12						; size = 8
__$ArrayPad$ = -4					; size = 4
_param1$ = 8						; size = 4
_param2$ = 12						; size = 4
_param3$ = 16						; size = 4
_func	PROC						; COMDAT

; 9    : {

	sub	esp, 12					; 0000000cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+12], eax

; 10   :   char buf[8];
; 11   :   gets(buf);

	lea	eax, DWORD PTR _buf$[esp+12]
	push	eax
	call	DWORD PTR __imp__gets

; 12   :   printf("%d %d %d %s\n", param1, param2, param3, buf);

	mov	edx, DWORD PTR _param3$[esp+12]
	mov	eax, DWORD PTR _param2$[esp+12]
	lea	ecx, DWORD PTR _buf$[esp+16]
	push	ecx
	mov	ecx, DWORD PTR _param1$[esp+16]
	push	edx
	push	eax
	push	ecx
	push	OFFSET ??_C@_0N@FGAKPGKN@?$CFd?5?$CFd?5?$CFd?5?$CFs?6?$AA@
	call	DWORD PTR __imp__printf

; 13   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+36]
	add	esp, 24					; 00000018H
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 12					; 0000000cH
	ret	0
_func	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 17   :   func(1, 2, 3);

	push	3
	push	2
	push	1
	call	_func
	add	esp, 12					; 0000000cH

; 18   :   return 0;

	xor	eax, eax

; 19   : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
