; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\Projects\TaintAnalysis\AntiTaint\Epilog\src\main.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_main
EXTRN	__imp__printf:PROC
EXTRN	__imp__gets:PROC
; Function compile flags: /Ogtpy
; File d:\projects\taintanalysis\antitaint\epilog\src\main.c
;	COMDAT _main
_TEXT	SEGMENT
_buf$ = -8						; size = 8
_main	PROC						; COMDAT

; 11   :   char buf[8];
; 12   :   gets(buf);

	lea	eax, DWORD PTR _buf$[esp]
	sub	esp, 8
	push	eax
	call	DWORD PTR __imp__gets

; 13   :   printf(buf);

	lea	ecx, DWORD PTR _buf$[esp+12]
	push	ecx
	call	DWORD PTR __imp__printf

; 14   :   return 0;

	xor	eax, eax

; 15   : }

	add	esp, 16					; 00000010H
	ret	0
_main	ENDP
_TEXT	ENDS
END
