; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\Projects\TaintAnalysis\AntiTaint\Epilog\src\struct-align.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_08OOHKHLPO@?$CFd?5?$CFd?5?$CFd?$AA@	; `string'
PUBLIC	_fill
EXTRN	__imp__scanf:PROC
;	COMDAT ??_C@_08OOHKHLPO@?$CFd?5?$CFd?5?$CFd?$AA@
; File d:\projects\taintanalysis\antitaint\epilog\src\struct-align.c
CONST	SEGMENT
??_C@_08OOHKHLPO@?$CFd?5?$CFd?5?$CFd?$AA@ DB '%d %d %d', 00H ; `string'
; Function compile flags: /Ogtp
CONST	ENDS
;	COMDAT _fill
_TEXT	SEGMENT
_c$ = -12						; size = 4
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_s$ = 8							; size = 4
_fill	PROC						; COMDAT

; 21   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH

; 22   :   int a, b, c;
; 23   :   scanf("%d %d %d", &a, &b, &c);

	lea	eax, DWORD PTR _c$[ebp]
	push	eax
	lea	ecx, DWORD PTR _b$[ebp]
	push	ecx
	lea	edx, DWORD PTR _a$[ebp]
	push	edx
	push	OFFSET ??_C@_08OOHKHLPO@?$CFd?5?$CFd?5?$CFd?$AA@
	call	DWORD PTR __imp__scanf

; 24   :   s->a = a;

	mov	ecx, DWORD PTR _s$[ebp]
	mov	eax, DWORD PTR _a$[ebp]
	cdq
	mov	DWORD PTR [ecx], eax

; 25   :   s->b = b;

	mov	eax, DWORD PTR _b$[ebp]
	mov	DWORD PTR [ecx+4], edx
	cdq
	mov	DWORD PTR [ecx+8], eax

; 26   :   s->c = c;

	mov	eax, DWORD PTR _c$[ebp]
	mov	DWORD PTR [ecx+12], edx
	cdq
	add	esp, 16					; 00000010H
	mov	DWORD PTR [ecx+16], eax
	mov	DWORD PTR [ecx+20], edx

; 27   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_fill	ENDP
_TEXT	ENDS
PUBLIC	??_C@_0N@DHODEHCL@?$CFs?5?$CFd?5?$CFd?5?$CFd?6?$AA@ ; `string'
PUBLIC	__$ArrayPad$
PUBLIC	_func
EXTRN	__imp__printf:PROC
EXTRN	__imp__gets:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
;	COMDAT ??_C@_0N@DHODEHCL@?$CFs?5?$CFd?5?$CFd?5?$CFd?6?$AA@
CONST	SEGMENT
??_C@_0N@DHODEHCL@?$CFs?5?$CFd?5?$CFd?5?$CFd?6?$AA@ DB '%s %d %d %d', 0aH
	DB	00H						; `string'
; Function compile flags: /Ogtp
CONST	ENDS
;	COMDAT _func
_TEXT	SEGMENT
_s$ = -64						; size = 32
_buf$ = -12						; size = 8
__$ArrayPad$ = -4					; size = 4
_func	PROC						; COMDAT

; 30   : {

	push	ebx
	mov	ebx, esp
	sub	esp, 8
	and	esp, -32				; ffffffe0H
	add	esp, 4
	push	ebp
	mov	ebp, DWORD PTR [ebx+4]
	mov	DWORD PTR [esp+4], ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax

; 31   :   struct S s;
; 32   :   char buf[8];
; 33   :   gets(buf);

	lea	eax, DWORD PTR _buf$[ebp]
	push	eax
	call	DWORD PTR __imp__gets

; 34   :   fill(&s);

	lea	ecx, DWORD PTR _s$[ebp]
	push	ecx
	call	_fill

; 35   :   printf("%s %d %d %d\n", buf, (int)s.a, (int)s.b, (int)s.c);

	mov	edx, DWORD PTR _s$[ebp+16]
	mov	eax, DWORD PTR _s$[ebp+8]
	mov	ecx, DWORD PTR _s$[ebp]
	push	edx
	push	eax
	push	ecx
	lea	edx, DWORD PTR _buf$[ebp]
	push	edx
	push	OFFSET ??_C@_0N@DHODEHCL@?$CFs?5?$CFd?5?$CFd?5?$CFd?6?$AA@
	call	DWORD PTR __imp__printf

; 36   : }

	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	add	esp, 28					; 0000001cH
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	mov	esp, ebx
	pop	ebx
	ret	0
_func	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 40   :   func();

	call	_func

; 41   :   return 0;

	xor	eax, eax

; 42   : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
